[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256
